//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int PmntId { get; set; }
        public int MtnId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PmntDate { get; set; }
        public string PmntMode { get; set; }
        public string PmntDetail { get; set; }
        public string PmntMadeBy { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Maintenance Maintenance { get; set; }
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
