//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Society()
        {
            this.Flats = new HashSet<Flat>();
            this.Owners = new HashSet<Owner>();
        }
    
        public int SocietyId { get; set; }
        public string Name { get; set; }
        public string BuilderName { get; set; }
        public string Address { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> TotalFlats { get; set; }
        public byte[] SocietyImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner> Owners { get; set; }
    }
}
