//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int id { get; set; }
        public int FlatId { get; set; }
        public int OwnerId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> DeregistrationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Person Person { get; set; }
    }
}
